### ISSUE TITLE
Get F distribution value given alpha, numerator and denominator degrees of variance

### ISSUE THREAD

**Issue by jahirfiquitiva** [padreati/rapaio#160]
Hello,
I am trying to implement your library for a project.
Everything is working really good, so thanks for creating this. Anyways, I need to get a value from the F distribution table given the alpha, the numerator degrees of variance, and the denominator degrees of variance.

Something like:  F<sub>0.025,9,14</sub>

Where:
α = 0.025
num = 9
den = 14

The output value here should be 3.2093 according to [this table](http://www.statisticshowto.com/tables/f-table/)

I am not sure if this is already possible and I just couldn't find the right class and method to call. If that's the case, would you mind explaining me what to use to achieve this?

If this isn't available yet, could you please consider this as a feature request?

Thanks again for such an amazing work.

**Comment by padreati** [comment]
Hi,

This is easily solved by the following code:
` Fisher f = new Fisher(9, 14);
  WS.println(f.quantile(1 - 0.025));
`
Now some meaning. Fisher is the class which implements methods for this distribution. When a new instance is created it will receive the degrees of freedom for numerator and demoninator. Thus we have new Fisher(9,14). Now in order to compute the p-value for your test, we have a critical value (0.025). This is the probability that an event is exceptional (not explained by chance). 

![](http://www.statisticshowto.com/wp-content/uploads/2013/09/f-table-300x166.jpg)

What you want is to find the value of the function F in some point, let's name it x, for which we will have the shaded area equal with alpha. This means in probabilities that we should have:
P(X > x) = alpha. But this is 1 - P(X<x) = alpha, and going further P(X<x) = 1- alpha. Now P(X<x) = cdf(x) is the cdf of F. The inverse of cdf is called quantile function. This means that we should have x = F.quantile(1-alpha). And that explains the second call.

Hope that helps. 
PS: in the meantime I noticed that the disctribution class was named Fischer, whcih of course is wrong, it should be Fisher. Now, after the last commit is correct.
PS2: a touched a lot of with the last commit, because I renamed the method Frame#var into Frame#rvar. Some of my friends like to use that code in Scala and there var is a reserved keyword. I hope I will not have to do many changes in the API soon.
PS3: When I will have time I will implement also the F test, so it will be much easier to have all the explanations.

Finally, thank you for taking time to look at the library and give feedback on that. If you want anything else or you have suggestions of any kind, please post them here so I can make it useful for you.

Best regards, Aurelian

**Comment by jahirfiquitiva** [comment]
Thank you. That snippet totally worked as expected

About what I would like to see...

Yeah, the F test would be helpful... but also if you could add some `boolean` methods to know whether the null hypothesis should be rejected or not and same for the alternative one.

Oh, and if you can make all numbers not appear with the E notation, so they are more readable. Or maybe add an option to that.

I think that'd be it.

Thank you so much for the quick reply :)

**Comment by padreati** [comment]
For showing values in different formats I had in plan to introduce printer options which can be given to any output facility and can dictate formats. This is already caught in an issue called printer options https://github.com/padreati/rapaio/issues/156. For exposing a boolean for test is is an awsome idea. A used only for investigation those tests, and in an interactive mode the text output was enough. However from a programmatic this is wrong. This is a really good idea and I will put an issue with that because I think you are right with this one. Thank you.
