### ISSUE TITLE
NumberFormatException in  XWilkinson.getList()

### ISSUE THREAD

**Issue by iromeo** [padreati/rapaio#167]
The issue occurs when using non-US locale. 

The bug is in:
```
// XWilkinson.getList()
list.add(Double.valueOf(String.format("%." + Math.abs(digits) + "f", i)));
```
Double.valueOf(..) allows only numbers with dot as fraction separator. In case of Russion or French locale String.format() returns '0,123'.

I suggest using `NumberFormat.getInstance().parse(String.format("%.4f", 0.123445)).doubleValue()`  to get consistent reuslts. Or replace String.fromat(..) with Formatter() which isn't locale specific.

To reproduce set local to non-us, e.g. add VM options
```
-Duser.language=ru
-Duser.country=RU
```
and run any code which invokes this method, e.g.
```
// kotlin
XWilkinson.base10(XWilkinson.DEEFAULT_EPS).searchBounded(0.0, 1.0, 5).list
```

P.S: Perhaps the same issue is not only in this method

**Comment by padreati** [comment]
Thank you for posting. I totally agree, I did not paid attention to  internationalization at all. I will have to do it everywhere, for sure. I need a little time to fix everywhere.

**Comment by iromeo** [comment]
You need this only to trim part of fraction part so may be better is just to multiply the value by `10 power digits`, round it and divide by `10 power digits`

**Comment by padreati** [comment]
I solved the issue and cleaned up some code there. The solution which I used is based on BigDecimal.valueOf. I considered some options:
- using String.format(Locale.US, ...) which works, but is slower and error prone since I had to find digits
- using double precision rounding like you propose, but gives wild results due to floating point artithmetics
- using new BigDecimal(double), but have similar problems with floating values
- using BigDecimal.valueOf which is similat with String.format but without me doing the digit arithmetic
Hope it works as expected now.

**Comment by iromeo** [comment]
Thank you, I’ll check this next week

**Comment by iromeo** [comment]
Do you have any plans to release new library version?

**Comment by iromeo** [comment]
> Hope it works as expected now.
The only issue is that the fixed version ignores locale settings, so instead of "0,4" user gets "0.4".

**Comment by padreati** [comment]
That deserves a separate issue. I think it is a whole discussion on that. Probably the correct way to do that is to allow all possibilities. Because it is related with other issues I would start a different issue with detailed discussion on that.
